### ISSUE TITLE
Try changing grafana_root_url

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud-infra/system-config#446]
According to https://grafana.com/tutorials/run-grafana-behind-a-proxy/ it is possible to set `root_url = %(protocol)s://%(domain)s:%(http_port)s`. Try whether it will work and apply if so to reduce hardcoding of the urls.

**Comment by kucerakk** [comment]
This does not seem to be an option in our case...setting individual parameters of the ```root_url``` especially the ```protocol``` to be set to ```https``` ... Grafana assumes itself has to run SSL and requires ```cert_file```

```msg="Server shutdown" logger=server error="*api.HTTPServer run error: cert_file cannot be empty when using HTTPS"```
