### ISSUE TITLE
Replace swift storage 1-3 nodes

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud-infra/system-config#738]
Reprovision storage[1-3] nodes to be matching [4-8] style (OS, FS setup, IPs). Reasons for reprovision are:
- better FS setup (dedicated /var/ part)
- newer OS
- faster disks
- newer flavor (faster cpu)

This needs to be done one by one including swift ring rebalancing:
- exclude node from ring files
- provision ring files and wait 24 hours
- reprovision node
- add new node to ring
- provision ring files and wait 24 hours
- repeat same for next node

storage1 is already removed from the ring and therefore can be safely replaced

**Comment by gtema** [comment]
https://github.com/opentelekomcloud-infra/system-config/pull/751

**Comment by gtema** [comment]
https://github.com/opentelekomcloud-infra/system-config/pull/755

**Comment by gtema** [comment]
Good, so now please prepare also inventory change for storage3.

Since we removed 2 and 3 from rings yesterday we can actually replace them both at once to save some rebalancing

**Comment by vladimirvshivkov** [comment]
https://github.com/opentelekomcloud-infra/system-config/pull/758

**Comment by vladimirvshivkov** [comment]
TODO:
add chown for swift
