### ISSUE TITLE
CH | PROD | WAF | GUI | help link "Learn more" shows error 404 or missing

### ISSUE THREAD

**Issue by mrogalo** [opentelekomcloud-infra/system-config#971]
**How to reproduce**
Affected:
Menu Web Application Firewall > Dashboard, point to question mark , click link "Learn more". After click error 404 page displayed.
Menu Web Application Firewall > Events, point to question mark , clink link "Learn more". After click error 404 page displayed.
Menu Web Application Firewall > Policies, point to question mark , click link "Learn more". After click error 404 page displayed.
Menu Web Application Firewall > Website Settings, point to question mark , click link "Learn more". After click error 404 page displayed.
affected & existing docu file:

https://docs.sc.otc.t-systems.com/en-us/usermanual/waf/waf_01_0021.html

https://docs.sc.otc.t-systems.com/en-us/usermanual/waf/waf_01_0018.html

https://docs.sc.otc.t-systems.com/en-us/usermanual/waf/waf_01_0055.html

https://docs.sc.otc.t-systems.com/en-us/usermanual/waf/waf_01_0067.html

**IDs of used resources**
account ID: 333a6c98344c45deb6b704402933a49a

**Result of the issue**
help link "Learn more" shows error 404 or missing

**Comment by vladimirhasko** [comment]
this is dedicated waf service and not shared waf service.
Therefore these links are available under:
https://docs.sc.otc.t-systems.com/en-us/usermanual/dwaf/waf_01_0021.html
https://docs.sc.otc.t-systems.com/en-us/usermanual/dwaf/waf_01_0018.html
https://docs.sc.otc.t-systems.com/en-us/usermanual/dwaf/waf_01_0055.html
https://docs.sc.otc.t-systems.com/en-us/usermanual/dwaf/waf_01_0067.html

Please ask vendor to change the links to correct ones in UI for dedicated WAF

**Comment by tischrei** [comment]
We cannot change the behavior from our side. For this purpose I will close the issue.

**Comment by mrogalo** [comment]
thank you. DWAF issue addressed fro vendor. (https://jira.tsi-dev.otc-service.com/browse/OTCSEC-6254)
