### ISSUE TITLE
EU-CH | PROD | IAM | GUI | help link "Learn more" shows error 404 or missing

### ISSUE THREAD

**Issue by mrogalo** [opentelekomcloud-infra/system-config#972]
Affected:

Menu IAM > Users , point to question mark , click link "Learn more". After click error 404 page displayed.
affected & existing docu file:  https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0046661675.html

Menu IAM > User Groups , point to question mark , click link "Learn more". After click error 404 page displayed.
https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0046611269.html

Menu IAM > Permissions > Policies/Roles, point to question mark , click link "Learn more". After click error 404 page displayed.
https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/iam_01_019.html

Menu IAM > Projects, point to question mark , click link "Learn more". After click error 404 page displayed.
https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0066738518.html

Menu IAM > Agencies, point to question mark , click link "Learn more". After click error 404 page displayed.
https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0046613147.html

Menu IAM > Identity Providers, point to question mark , click link "Learn more". After click error 404 page displayed.
https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0079620341.html

Menu IAM > Security Settings, point to question mark , click link "Learn more". After click error 404 page displayed.
https://docs.sc.otc.t-systems.com/en-us/usermanual/iam/en-us_topic_0046611308.html

**IDs of used resources**
account ID: 333a6c98344c45deb6b704402933a49a

**Result of the issue**
help link "Learn more" shows error 404 or missing

**Comment by vladimirhasko** [comment]
Fixing by #974

**Comment by vladimirhasko** [comment]
fixed
